version: '3.4'

services:
  postgres:
    container_name: twitter_db
    image: postgres
    ports:
      -5432:5432
    volumes:
      -postgres_data:/var/lib/postgressql/data
    environment:
      - POSTGRES_USER=postgres

volumes:
    postgres_data: